# Generated by Django 3.2.4 on 2021-06-24 14:15

import Anudan.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Municipality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyakram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Municipality.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Karyakram',
                'verbose_name_plural': 'Karyakram',
                'db_table': 'Karyakram',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Samagri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('quantity', models.IntegerField(default=1)),
                ('karyakram', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Anudan.karyakram', verbose_name='Karyakram')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Anudan.unit', verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Samagri',
                'verbose_name_plural': 'Samagri',
                'db_table': 'Samagri',
                'ordering': ['karyakram'],
            },
        ),
        migrations.CreateModel(
            name='AnudanPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('ward', models.PositiveIntegerField(max_length=2, verbose_name='Ward')),
                ('tole', models.CharField(max_length=255, verbose_name='Tole')),
                ('nagrikta_number', models.PositiveBigIntegerField(max_length=12, verbose_name='Nagrikta Number')),
                ('jari_jilla', models.CharField(max_length=20, verbose_name='Jaari Jilla')),
                ('nagrikta_front', models.ImageField(upload_to=Anudan.models.personal_location, verbose_name='Nagrikta Front Photo')),
                ('nagrikta_back', models.ImageField(blank=True, upload_to=Anudan.models.personal_location, verbose_name='Nagrikta Back Photo')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=14, verbose_name='Approval')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.fiscalyear', verbose_name='Fiscal Year')),
                ('karyakram', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Anudan.karyakram', verbose_name='Karyakram')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Municipality.municipality', verbose_name='Municipality')),
                ('samagri', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='karyakram', chained_model_field='karyakram', on_delete=django.db.models.deletion.PROTECT, to='Anudan.samagri', verbose_name='Samagri')),
            ],
            options={
                'verbose_name': 'Anudan Personal',
                'verbose_name_plural': 'Anudan Personal',
                'db_table': 'Anudan_Personal',
            },
        ),
        migrations.CreateModel(
            name='AnudanCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255, verbose_name='Firm name')),
                ('pan_no', models.PositiveIntegerField(max_length=2, verbose_name='PAN no')),
                ('vat_no', models.CharField(max_length=255, verbose_name='VAT no')),
                ('registration_no', models.PositiveBigIntegerField(max_length=12, verbose_name='Registration Number')),
                ('ward', models.PositiveIntegerField(max_length=2, verbose_name='Ward')),
                ('tole', models.CharField(max_length=255, verbose_name='Tole')),
                ('registered_place', models.CharField(max_length=20, verbose_name='Jaari Jilla')),
                ('anya_darta', models.CharField(blank=True, choices=[('Gharelu', 'Gharelu'), ('Vanijya', 'Vanijya')], max_length=50, null=True, verbose_name='Registered as')),
                ('firm_registration_proof', models.ImageField(upload_to=Anudan.models.company_location, verbose_name='Firm Registration Proof')),
                ('ward_sifaris', models.ImageField(upload_to=Anudan.models.company_location, verbose_name='Ward Sifaris')),
                ('prastavan', models.ImageField(upload_to=Anudan.models.company_location, verbose_name='Upload Prastavan')),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=14, verbose_name='Approval')),
                ('fiscal_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Accounts.fiscalyear', verbose_name='Fiscal Year')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Municipality.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Anudan Company',
                'verbose_name_plural': 'Anudan Company',
                'db_table': 'Anudan_Company',
            },
        ),
    ]
