# Generated by Django 3.2.4 on 2021-06-26 11:33

import Anudan.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Municipality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyakram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Municipality.municipality', verbose_name='Municipality')),
                ('sector', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Municipality.sector', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Karyakram',
                'verbose_name_plural': 'Karyakram',
                'db_table': 'Karyakram',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'db_table': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('contact_number', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('tole', models.CharField(max_length=150, verbose_name='Tole')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Municipality.municipality', verbose_name='Municipality')),
                ('ward', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Municipality.ward', verbose_name='Ward')),
            ],
            options={
                'verbose_name': 'Medicine Request',
                'verbose_name_plural': 'Medicine Request',
                'db_table': 'Medicine_Request',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'Unit',
            },
        ),
        migrations.CreateModel(
            name='Samagri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('karyakram', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Anudan.karyakram', verbose_name='Karyakram')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Anudan.unit', verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Samagri',
                'verbose_name_plural': 'Samagri',
                'db_table': 'Samagri',
                'ordering': ['karyakram'],
            },
        ),
        migrations.CreateModel(
            name='MedicineRequested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Quantity')),
                ('medicine', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, related_name='Medicines_Requested', to='Anudan.medicine', verbose_name='Medicine')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicines_Requested', to='Anudan.medicinerequest', verbose_name='Requested By')),
            ],
        ),
        migrations.CreateModel(
            name='AnudanPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('tole', models.CharField(max_length=150, verbose_name='Tole')),
                ('nagrikta_number', models.CharField(max_length=20, verbose_name='Nagrikta Number')),
                ('nagrikta_front', models.ImageField(upload_to=Anudan.models.personal_location, verbose_name='Nagrikta Front Photo')),
                ('nagrikta_back', models.ImageField(blank=True, upload_to=Anudan.models.personal_location, verbose_name='Nagrikta Back Photo')),
                ('jari_jilla', models.CharField(max_length=20, verbose_name='Jaari Jilla')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=14, verbose_name='Approval')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounts.fiscalyear', verbose_name='Fiscal Year')),
                ('karyakram', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sector', chained_model_field='sector', on_delete=django.db.models.deletion.PROTECT, to='Anudan.karyakram', verbose_name='Karyakram')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Municipality.municipality', verbose_name='Municipality')),
                ('samagri', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='karyakram', chained_model_field='karyakram', on_delete=django.db.models.deletion.PROTECT, to='Anudan.samagri', verbose_name='Samagri')),
                ('sector', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Municipality.sector', verbose_name='Sector')),
                ('ward', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Municipality.ward', verbose_name='Ward')),
            ],
            options={
                'verbose_name': 'Anudan Personal',
                'verbose_name_plural': 'Anudan Personal',
                'db_table': 'Anudan_Personal',
            },
        ),
        migrations.CreateModel(
            name='AnudanCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255, verbose_name='Firm name')),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN no')),
                ('vat_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='VAT no')),
                ('registration_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='Registration Number')),
                ('tole', models.CharField(max_length=150, verbose_name='Tole')),
                ('registered_place', models.CharField(max_length=20, verbose_name='Jaari Jilla')),
                ('anya_darta', models.CharField(blank=True, choices=[('Gharelu', 'Gharelu'), ('Banijya', 'Banijya')], max_length=50, null=True, verbose_name='Registered as')),
                ('firm_registration_proof', models.ImageField(upload_to=Anudan.models.company_location, verbose_name='Firm Registration Proof')),
                ('ward_sifaris', models.ImageField(upload_to=Anudan.models.company_location, verbose_name='Ward Sifaris')),
                ('prastavan', models.ImageField(upload_to=Anudan.models.company_location, verbose_name='Upload Prastavan')),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=14, verbose_name='Approval')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateField(auto_now=True, verbose_name='updated')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Accounts.fiscalyear', verbose_name='Fiscal Year')),
                ('karyakram', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sector', chained_model_field='sector', on_delete=django.db.models.deletion.PROTECT, to='Anudan.karyakram', verbose_name='Karyakram')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Municipality.municipality', verbose_name='Municipality')),
                ('sector', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Municipality.sector', verbose_name='Sector')),
                ('ward', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Municipality.ward', verbose_name='Ward')),
            ],
            options={
                'verbose_name': 'Anudan Company',
                'verbose_name_plural': 'Anudan Company',
                'db_table': 'Anudan_Company',
            },
        ),
    ]
