# Generated by Django 3.2.4 on 2021-06-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anudancompany',
            name='contact_number',
            field=models.CharField(default=0, max_length=20, verbose_name='Contact Number'),
        ),
    ]
