# Generated by Django 3.2.4 on 2021-06-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nagarpalika',
            name='contact_number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
