# Generated by Django 3.2.4 on 2021-06-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anudancompany',
            options={'verbose_name': 'Anudan Company', 'verbose_name_plural': 'Anudan Company'},
        ),
        migrations.AlterModelOptions(
            name='anudanpersonal',
            options={'verbose_name': 'Anudan Personal', 'verbose_name_plural': 'Anudan Personal'},
        ),
        migrations.AlterModelOptions(
            name='karyakram',
            options={'verbose_name': 'Karyakram', 'verbose_name_plural': 'Karyakram'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Municipality', 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AlterModelOptions(
            name='samagri',
            options={'ordering': ['karyakram'], 'verbose_name': 'Samagri', 'verbose_name_plural': 'Samagri'},
        ),
        migrations.AlterField(
            model_name='karyakram',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='karyakram',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='karyakram',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='update'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='contact_number',
            field=models.CharField(default=0, max_length=10, verbose_name='phonenumber'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='samagri',
            name='name',
            field=models.CharField(help_text='Enter Samagri to Add', max_length=255, verbose_name='name'),
        ),
    ]
