# Generated by Django 3.2.4 on 2021-06-24 14:26

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Municipality', '0001_initial'),
        ('Anudan', '0002_karyakram_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='anudanpersonal',
            name='sector',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', default=1, on_delete=django.db.models.deletion.PROTECT, to='Municipality.sector', verbose_name='Sector'),
        ),
    ]
