# Generated by Django 3.2.4 on 2021-06-20 07:53

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0002_auto_20210620_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anudancompany',
            old_name='nagarpalika',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='anudanpersonal',
            old_name='nagarpalika',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='karyakram',
            old_name='nagarpalika',
            new_name='municipality',
        ),
        migrations.RenameField(
            model_name='samagri',
            old_name='nagarpalika',
            new_name='municipality',
        ),
        migrations.AlterField(
            model_name='anudanpersonal',
            name='karyakram',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Anudan.karyakram'),
        ),
        migrations.AlterField(
            model_name='samagri',
            name='karyakram',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='municipality', chained_model_field='municipality', on_delete=django.db.models.deletion.PROTECT, to='Anudan.karyakram'),
        ),
    ]
