# Generated by Django 3.2.4 on 2021-06-14 12:09

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0002_nagarpalika_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samagri',
            name='karyakram',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='nagarpalika', chained_model_field='nagarpalika', on_delete=django.db.models.deletion.CASCADE, to='Anudan.karyakram'),
        ),
    ]
