# Generated by Django 3.2.4 on 2021-06-25 09:35

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0003_anudanpersonal_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anudancompany',
            name='anya_darta',
            field=models.CharField(blank=True, choices=[('Gharelu', 'Gharelu'), ('Banijya', 'Banijya')], max_length=50, null=True, verbose_name='Registered as'),
        ),
        migrations.AlterField(
            model_name='anudanpersonal',
            name='karyakram',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sector', chained_model_field='sector', on_delete=django.db.models.deletion.PROTECT, to='Anudan.karyakram', verbose_name='Karyakram'),
        ),
    ]
