# Generated by Django 3.2.4 on 2021-06-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Municipality', '0001_initial'),
        ('Anudan', '0004_auto_20210625_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anudancompany',
            name='pan_no',
            field=models.PositiveBigIntegerField(verbose_name='PAN no'),
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='registration_no',
            field=models.PositiveBigIntegerField(verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='vat_no',
            field=models.PositiveBigIntegerField(verbose_name='VAT no'),
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='ward',
            field=models.PositiveSmallIntegerField(verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='anudanpersonal',
            name='nagrikta_number',
            field=models.PositiveBigIntegerField(verbose_name='Nagrikta Number'),
        ),
        migrations.AlterField(
            model_name='anudanpersonal',
            name='ward',
            field=models.PositiveIntegerField(verbose_name='Ward'),
        ),
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('ward', models.PositiveSmallIntegerField(verbose_name='Ward')),
                ('tole', models.CharField(max_length=150, verbose_name='Tole')),
                ('medicine', models.CharField(max_length=150, verbose_name='Medicine')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Municipality.municipality', verbose_name='Municipality')),
            ],
        ),
    ]
