# Generated by Django 3.2.4 on 2021-06-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0005_auto_20210615_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnudanPerosnal',
            new_name='AnudanPersonal',
        ),
    ]
