# Generated by Django 3.2.4 on 2021-06-24 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0005_alter_anudanpersonal_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samagri',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Anudan.unit', verbose_name='Units'),
        ),
    ]
