# Generated by Django 3.2.4 on 2021-06-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0006_alter_samagri_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='anudancompany',
            name='anya_darta',
            field=models.CharField(default='', max_length=50),
        ),
    ]
