# Generated by Django 3.2.4 on 2021-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0008_auto_20210624_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anudancompany',
            name='anya_darta',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
