# Generated by Django 3.2.4 on 2021-06-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0012_alter_anudancompany_fiscal_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anudancompany',
            name='anya_darta',
        ),
    ]
