# Generated by Django 3.2.4 on 2021-06-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anudan', '0013_remove_anudancompany_anya_darta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anudancompany',
            name='fiscal_year',
        ),
        migrations.RemoveField(
            model_name='anudancompany',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=14),
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='firm_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Anudan.municipality'),
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='pan_no',
            field=models.PositiveIntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='tole',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='vat_no',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='anudancompany',
            name='ward',
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
