# Generated by Django 3.2.4 on 2021-06-13 11:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palikauser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 6, 13, 11, 46, 41, 924999, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.PositiveBigIntegerField(blank=True, verbose_name='Contact Number'),
        ),
    ]
