# Generated by Django 3.2.4 on 2021-06-20 07:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipalitystaff',
            options={'verbose_name_plural': 'Staffs'},
        ),
        migrations.RenameField(
            model_name='municipalitystaff',
            old_name='palika',
            new_name='municipality',
        ),
        migrations.AlterField(
            model_name='palikauser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 6, 20, 7, 52, 8, 24673, tzinfo=utc)),
        ),
    ]
