# Generated by Django 3.2.4 on 2021-06-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_palikauser_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palikauser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='palikauser',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
