# Generated by Django 3.2.4 on 2021-06-13 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anudaan', '0001_initial'),
        ('Accounts', '0002_auto_20210613_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palika',
            name='palika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anudaan.nagarpalika'),
        ),
        migrations.AlterField(
            model_name='palikauser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 6, 13, 11, 48, 37, 169961, tzinfo=utc)),
        ),
    ]
