# Generated by Django 3.2.4 on 2021-06-14 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210614_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palikauser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 6, 14, 12, 9, 43, 794329, tzinfo=utc)),
        ),
    ]
