# Generated by Django 3.2.4 on 2021-06-23 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_palikauser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palikauser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 6, 23, 16, 8, 4, 91226, tzinfo=utc), verbose_name='date joined'),
        ),
    ]
