# Generated by Django 3.2.4 on 2021-06-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('contact_number', models.CharField(default=0, max_length=10, verbose_name='Contact Number')),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'db_table': 'Municipality',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Municipality.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Ward',
                'db_table': 'Ward',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Municipality.municipality', verbose_name='Municipality')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'Sector',
            },
        ),
    ]
